stages:
  - build
  - test
  - publish
  - deploy

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/Auction_backend/.m2/repository"

cache:
  paths:
    - $CI_PROJECT_DIR/Auction_backend/.m2/repository

build_frontend:
  stage: build
  image: node:latest
  before_script:
    - cd Auction_frontend/
  script:
    - echo "build frontEnd"
    - npm install --legacy-peer-deps
    - npm install -g @angular/cli
    - ng build
  artifacts:
    paths:
      - Auction_frontend/dist/auction-frontend/
  tags:
    - auctionrunner
    
build_backend:
  stage: build
  image: maven:3.9.7-sapmachine-17
  before_script:
    - cd Auction_backend/
  script:
    - echo "Build backend"
    - mvn clean install -DskipTests
  artifacts:
    paths:
      - Auction_backend/target/
  tags:
    - auctionrunner

test_backend:
  stage: test
  image: maven:3.9.7-sapmachine-17
  before_script:
    - cd Auction_backend/
  script:
    - echo "Loading the cache directory"
    - echo $CI_PROJECT_DIR/Auction_backend/.m2/repository
    - echo "Running Tests"
    - mvn test
  tags:
    - auctionrunner

publish_backend:
  stage: publish
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  before_script:
    - cd Auction_backend/
  script:
    - echo $DOCKER_HOST
    - docker --version
    - echo "Logging Docker"
    #- echo $DOCKER_PASSWORD |docker login -u $DOCKER_USERNAME --password-stdin
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - echo "Building the Docker image for the Backend"
    - docker build -t docker.io/$DOCKER_USERNAME/auctionbackend .
    - echo "Successfully build the docker image for the backend"
    - docker push docker.io/$DOCKER_USERNAME/auctionbackend
  after_script:
    - echo "Docker Image pushed successfully"
    - docker logout
  when: manual
  tags:
    - auctionrunner

publish_frontend:
  stage: publish
  image: docker:latest
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  before_script:
    - cd Auction_frontend/
  script:
    - echo $DOCKER_HOST
    - docker --version
    - echo "Logging Docker"
    #- echo $DOCKER_PASSWORD |docker login -u $DOCKER_USERNAME --password-stdin
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - echo "Building the Docker image"
    - docker build -t docker.io/$DOCKER_USERNAME/auctionfrontend .
    - echo "Successfully build the docker image"
    - docker push docker.io/$DOCKER_USERNAME/auctionfrontend
  after_script:
    - echo "Docker Image pushed successfully"
    - docker logout
  when: manual
  tags:
    - auctionrunner

deploy_build:
  image: alpine:latest
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts 
  script:  
    - ssh $SSH_USER@$VM_IPADDRESS "hostname && echo 'Welcome!!!' > welcome.txt"
    - ssh $SSH_USER@$VM_IPADDRESS "docker container rm -f auctionfrontend || true"
    - ssh $SSH_USER@$VM_IPADDRESS "docker container rm -f auctionbackend || true"
    - ssh $SSH_USER@$VM_IPADDRESS "docker run -d -p4200:4200 --name auctionfrontend  $DOCKER_USERNAME/auctionfrontend"
    - ssh $SSH_USER@$VM_IPADDRESS "docker run -d -p8080:8080 --name auctionbackend $DOCKER_USERNAME/auctionbackend"
  when: manual
  tags:
    - dalfcs_docker_kvm